export const COACHES = [
  {
    id: 'pyg-001',
    name: '박용군',
    initial: '박',
    title: '1호 코치',
    industry: '외식업 (족발)',
    region: '경기 평택',
    years: 10,
    failType: '코로나 매출 급감',
    skills: ['신용회복', '법무', '권리금 협상', '직원 정리'],
    bio: '평택 부용로에서 10년간 족발집을 운영하다 2021년 코로나 매출 급감으로 폐업. 5년 전 본인이 직접 헤맸던 30개 절차를 후배 사장님에게 4주 동안 손잡고 안내합니다. 현재 부동산 임대업 병행, 배우자가 동네 카페 운영 중이라 자영업 생태계와 매일 접점.',
    featured: true,
  },
  {
    id: 'kim-002',
    name: '김도현',
    initial: '김',
    title: '카페 8년 폐업 코치',
    industry: '외식업 (카페)',
    region: '경기 수원',
    years: 8,
    failType: '임대료 상승',
    skills: ['임대차 분쟁', '권리금 회수', '세무'],
    bio: '수원 골목 카페 8년 운영, 2023년 임대료 인상으로 폐업. 권리금 회수 분쟁 직접 경험.',
  },
  {
    id: 'lee-003',
    name: '이현주',
    initial: '이',
    title: '미용실 12년 폐업 코치',
    industry: '서비스업 (미용)',
    region: '경기 성남',
    years: 12,
    failType: '직원 인건비',
    skills: ['직원 정리', '4대보험', '재취업'],
    bio: '성남 분당 미용실 12년 운영 후 인건비 압박으로 폐업. 직원 5명 단계적 정리 노하우 보유.',
  },
  {
    id: 'choi-004',
    name: '최영수',
    initial: '최',
    title: '편의점 6년 폐업 코치',
    industry: '유통 (편의점)',
    region: '경기 안양',
    years: 6,
    failType: '본사 정산 분쟁',
    skills: ['프랜차이즈 분쟁', '재고 정리', '신용회복'],
    bio: '안양 편의점 6년 운영 후 본사 정산 분쟁으로 폐업. 프랜차이즈 본사 협상 경험 다수.',
  },
  {
    id: 'jung-005',
    name: '정민수',
    initial: '정',
    title: '학원 9년 폐업 코치',
    industry: '교육 (보습학원)',
    region: '경기 용인',
    years: 9,
    failType: '학생 수 감소',
    skills: ['교육법 폐원 절차', '강사 정리', '환불 처리'],
    bio: '용인 보습학원 9년 운영 후 학령인구 감소로 폐원. 학원 폐원 행정 절차 전문.',
  },
  {
    id: 'song-006',
    name: '송혜진',
    initial: '송',
    title: '꽃집 7년 폐업 코치',
    industry: '소매 (생화)',
    region: '경기 오산',
    years: 7,
    failType: '온라인 경쟁',
    skills: ['재고 처분', '온라인 전환', '세무'],
    bio: '오산 꽃집 7년 운영 후 온라인 플랫폼 경쟁으로 폐업. 재고 처분·라이브커머스 경험.',
  },
];
